use walkdir::WalkDir;

fn main(){
    for (index,filelist) in WalkDir::new("./src").into_iter().enumerate(){
        let entry = filelist.unwrap();
        println!(" {}. {:?} ",index,entry.path().display());
    }
}

//Output is like ::::
//                0. "./src" 
//                1. "./src/Packages.rs" 
//                2. "./src/RandCrate.rs" 
//                3. "./src/MutableReference.rs" 
//                4. "./src/Closures.rs" 
//                5. "./src/ChronoDateTimes.rs" 
//                6. "./src/Numbers.rs" 
//                7. "./src/CrossTermManpltn" 
//                8. "./src/CrossTermManpltn/KeyEvents.rs" 
//                9. "./src/CrossTermManpltn/MoveToCursor.rs" 
//                10. "./src/CrossTermManpltn/BgAndFgColors.rs" 
//                11. "./src/CrossTermManpltn/SimplePrintTerminal.rs" 
//                12. "./src/Conditionals" 
//                13. "./src/FileHandlings" 
//                14. "./src/FileHandlings/OpenOptions.rs" 
//                15. "./src/FileHandlings/Mutiplication1To10WriteRead.rs" 
//                16. "./src/FileHandlings/BasicReadWrite.rs" 
//                17. "./src/FileHandlings/AsyncHandlings.rs" 
//                18. "./src/Numbers" 
//                19. "./src/JoinAndSpawnForConcurrency.rs" 
//                20. "./src/OddEven.rs" 
//                21. "./src/ThreadClosureOwnership.rs" 
//                22. "./src/TypeSafety.rs" 
//                23. "./src/Booleans.rs" 
//                24. "./src/AsyncAwait.rs" 
//                25. "./src/LifeTimeDisplayQuestion.rs" 
//                26. "./src/StringvsSlice.rs" 
//                27. "./src/StringFunctions.rs" 
//                28. "./src/Results.rs" 
//                29. "./src/MutableReferenceProblems.rs" 
//                30. "./src/Booleans" 
//                31. "./src/Options.rs" 
//                32. "./src/Functions.rs" 
//                33. "./src/VectorsExample.rs" 
//                34. "./src/Box.rs" 
//                35. "./src/RataTUi" 
//                36. "./src/RataTUi/SimpleRectDisplay.rs" 
//                37. "./src/RataTUi/SimpleLayoutDivide.rs" 
//                38. "./src/RataTUi/MultipleLines.rs" 
//                39. "./src/RataTUi/UserInputHandling.rs" 
//                40. "./src/RataTUi/Lists.rs" 
//                41. "./src/RataTUi/KeyUpDown.rs" 
//                42. "./src/RataTUi/Charts.rs" 
//                43. "./src/RataTUi/TwoBytwoBox.rs" 
//                44. "./src/RataTUi/navBarsAndContents.rs" 
//                45. "./src/RataTUi/Tables.rs" 
//                46. "./src/RataTUi/ProgressBar.rs" 
//                47. "./src/EnumsInRust.rs" 
//                48. "./src/ReturningTuple.rs" 
//                49. "./src/LifeTimesStruct.rs" 
//                50. "./src/MultiThreading.rs" 
//                51. "./src/Fibonaccu.rs" 
//                52. "./src/AdaptersInIterations.rs" 
//                53. "./src/OwnershipRules.rs" 
//                54. "./src/String.rs" 
//                55. "./src/HelloWorld.rs" 
//                56. "./src/TraitBounds.rs" 
//                57. "./src/IterationsQuesion.rs" 
//                58. "./src/DynDispatch.rs" 
//                59. "./src/TokioSpawn.rs" 
//                60. "./src/main.rs" 
//                61. "./src/Functions" 
//                62. "./src/loops" 
//                63. "./src/Iterators.rs" 
//                64. "./src/LifeTimesBasic.rs" 
//                65. "./src/VectorFunctions.rs" 
//                66. "./src/LifeTimesBasic02.rs" 
//                67. "./src/String" 
//                68. "./src/Conditionals.rs" 
//                69. "./src/Traits.rs" 
//                70. "./src/Factorial.rs" 
//                71. "./src/BorrowWithReference.rs" 
//                72. "./src/HashmapXvectorsQstn.rs" 
//                73. "./src/loops.rs" 
//                74. "./src/structsBasic.rs" 
//                75. "./src/ThreadMPSC.rs" 
//                76. "./src/mod" 
//                77. "./src/mod/lol.rs" 
//                78. "./src/mod/main_.rs" 
//                79. "./src/TraitAsParams.rs" 
//                80. "./src/MultiThreading02.rs" 
//                81. "./src/Practices" 
//                82. "./src/Practices/TodoList.rs" 
//                83. "./src/Practices/SwitchCaseThingee.rs" 
//                84. "./src/Practices/TodoCLI.rs" 
//                85. "./src/Practices/MathQuiz.rs" 
//                86. "./src/Practices/DateDifference.rs" 
//                87. "./src/Practices/LogsGenerator.rs" 
//                88. "./src/Hashmaps.rs" 
//                89. "./src/MathFunctions.rs" 
//                90. "./src/FunctionImpOnStructs.rs" 